server:
  port: 8080
spring:
  application:
    name: bs-manage-web
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
simple:
  mybatis:
    useRecordStatus: true # 开启数据库逻辑删除字段
unicLogger:
  httpFilter:
    urlPatterns: /bs/*,/app/* # traceId过滤器拦截路径
logging:
  level:
    com.hb.bsmanage.web: info
    com.hb.mybatis.mapper: debug
    com.hb.bsmanage.dao.mapper: debug
  file:
    path: /log/bs-manage-web/
jasypt:
  encryptor:
    password: bs_manage_web # jasypt加密的key
security:
  ignoreUrlPatterns: # springsecurity忽略的url
      - /bs/noauth/**
jwt:
  config:
    key: bs_manage_web  # jwt签名key
    defaultTtl: 60000000  # jwt默认过期时间1000分钟
    rememberMeTtl: 604800000  # jwt记住我时的过期时间
mybatis:
  mapper-locations: classpath*:mapper/*.xml
