server:
  port: 8080
spring:
  application:
    name: bs-manage-web
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
#################################################### simple-mybatis ####################################################
simple:
  mybatis:
    hump_mapping: false
#################################################### unic-logger ####################################################
unicLogger:
  httpFilter:
    urlPatterns: /controller/*,/app/*