### get
GET http://localhost:8080/controller/test/testGet?userName=zhangsan
Accept: */*
Cache-Control: no-cache

### post
POST http://localhost:8080/controller/test/testPost
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"userName":"zhangsan"}

###

