### 获取下拉框
GET http://localhost:8080/bs/noauth/tools/combobox/ResourceType
Accept: */*
Cache-Control: no-cache

### 设置redis缓存
POST http://localhost:8080/bs/noauth/tools/redis/set/testKey/600
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"userName":"zhangsan"}

### 获取redis缓存
GET http://localhost:8080/bs/noauth/tools/redis/get/bs-managejwt:token:huangbiao
Accept: */*
Cache-Control: no-cache

### 清除redis缓存
GET http://localhost:8080/bs/noauth/tools/redis/clear/bs-managejwt:token:huangbiao
Accept: */*
Cache-Control: no-cache

