### 添加用户
POST http://localhost:8080/bs/noauth/user/addOne
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"userName":"huangbiao","password":"123456","mobile":"18310673000"}

### 查找用户
POST http://localhost:8080/bs/auth/user/findOne
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJVMSIsInN1YiI6Imh1YW5nYmlhbyIsImlhdCI6MTU5OTIxMjAyMCwiZXhwIjoxNTk5MjE4MDIwfQ.on33rce9hhZCxFx6UzPpy3_SMI90kig4C8a2t1-usw8

{"userId":"1234567","mobile":"1234567"}

###

### 根据用户id或者手机号查找用户
GET http://localhost:8080/bs/noauth/user/findByUserIdOrMobile?userIdOrMobile=1234567
Accept: */*
Cache-Control: no-cache

###

### 根据主键查找用户
POST http://localhost:8080/bs/noauth/user/findById
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":1}

###

### 查找用户
POST http://localhost:8080/bs/noauth/user/findList
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"userId":"1234567","mobile":"1234567"}

###

### 查找用户
POST http://localhost:8080/bs/noauth/user/findPages
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"userId":"1234567","mobile":"1234567"}

###

